name: Build PrintFlow X

on:
  workflow_dispatch:
  push:
    branches:
      - principal
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Instalar dependências
        run: flutter pub get

      - name: Compilar APK
        run: flutter build apk --release

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: printflow-x-apk
          path: build/app/outputs/flutter-apk/app-release.apk
